#[Optional] Donne un nom dans l'onglet Actions
name: Java CI test build

#[Required] Trigger events, cette action agit selon les events suivants
# ici, lors d'un push ou d'une pull_request (merge), sur la branche "master"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

#[Required] peut avoir plusieurs ou un seul job
# Un job regroupe une séquence d'étapes à effectuer (steps)
jobs:
    build:
      # environnement
      runs-on: ubuntu-latest
      # [Required] utilise "uses" pour selectionner une action ou "run" pour lancer une commande (e.g "ls")
      steps:
      # "actions/" est un répo qui regroupe des actions déjà existante. Celle ci checker le répository
      - uses: actions/checkout@v3
      
      # Nom du step
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Test
        run: mvn -B test --file pom.xml

      - name: Build
        run: mvn -B package -Dmaven.test.skip --file pom.xml
      
      - name: Login to Docker Hub
        env:
          secret_usrn: ${{ secrets.DOCKERHUB_USERNAME }}
          secret_pwd: ${{ secrets.DOCKERHUB_TOKEN }}
        uses: docker/login-action@v2
        with:
          
          username: $secret_usrn
          password: $secret_pwd
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ci_cd_pipeline:latest
          

        
    
