# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: potit test

on:
  push:
    branches: [ "master" ]
  

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v3
    - name: testrugikio
      run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.POTOT  }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.POTOT }} | sed 's/./& /g' 


